import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
const git=(args)=>execFileSync('git',args,{encoding:'utf8',windowsHide:true}).trim();
if(resolve(git(['rev-parse','--show-toplevel']))!==process.cwd())throw Error('Run packaging from the repository root.');
if(git(['status','--porcelain','--untracked-files=normal']))throw Error('Source packaging requires a clean committed tree.');
const metadata=JSON.parse(readFileSync('package.json','utf8'));
const version=metadata.version;
if(metadata.name!=='safe'||metadata.license!=='MIT'||!/^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$/.test(version))throw Error('Expected stable Safe version and MIT metadata.');
const commit=git(['rev-parse','HEAD']);
if(process.env.GITHUB_SHA&&process.env.GITHUB_SHA!==commit)throw Error('Checkout differs from the workflow commit.');
const directory=resolve('release-artifacts');mkdirSync(directory,{recursive:true});
const filename=`safe_${version}_source.zip`,output=resolve(directory,filename);
execFileSync('git',['-c','core.autocrlf=false','archive','--format=zip',`--prefix=safe-${version}/`,`--output=${output}`,'HEAD'],{windowsHide:true});
const checksum=createHash('sha256').update(readFileSync(output)).digest('hex')+'  '+filename+'\n';
writeFileSync(output+'.sha256',checksum);writeFileSync(resolve(directory,'SHA256SUMS'),checksum);
console.log(`Packaged ${filename} from ${commit}`);
